const Model = require('objection').Model;
const BaseModel = require('./baseModel');

class EmailVerification extends BaseModel {
    static get tableName() {
        return 'emailVerifications';
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                id: { type: 'string' },
                userEmailId: { type: 'string' },
                createdAt : { type: 'dateTime' }
            }
        };
    }

    static get relationMappings() {
        const UserEmail = require('./userEmail');

        return {
            userEmail: {
                relation: Model.HasOneRelation,
                modelClass: UserEmail,
                join: {
                    from: 'emailVerifications.userEmailId',
                    to: 'userEmails.id'
                }
            }
        };
    }
}

module.exports = EmailVerification;
