const Model = require('objection').Model;
const BaseModel = require('./baseModel');

class ForgotPassword extends BaseModel {
    static get tableName() {
        return 'forgotPasswords';
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                id: { type: 'string' },
                userId: { type: 'string' },
                userEmailId: { type: 'string' },
                createdAt: { type: 'dateTime' },
                triggeredAt: { type: 'dateTime' }
            }
        };
    }

    static get relationMappings() {
        const UserEmail = require('./userEmail');
        const User = require('./user');

        return {
            userEmail: {
                relation: Model.HasOneRelation,
                modelClass: UserEmail,
                join: {
                    from: 'forgotPasswords.userEmailId',
                    to: 'userEmails.id'
                }
            },
            user: {
                relation: Model.HasOneRelation,
                modelClass: User,
                join: {
                    from: 'forgotPasswords.userId',
                    to: 'users.id'
                }
            }
        };
    }
}

module.exports = ForgotPassword;