const Model = require('objection').Model;
const BaseModel = require('./baseModel');

class Organization extends BaseModel {
    static get tableName() {
        return 'organizations';
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                personal: { type: 'boolan' },
                deleted: { type: 'boolan' }
            }
        };
    }

    static get relationMappings() {
        const UserOrganization = require('./userOrganization');
        const OrganizationApplication = require('./organizationApplication');

        return {
            organizationApplications: {
                relation: Model.HasManyRelation,
                modelClass: OrganizationApplication,
                join: {
                    from: 'organizations.id',
                    to: 'organizationApplications.organizationId'
                }
            },
            userOrganizations: {
                relation: Model.HasManyRelation,
                modelClass: UserOrganization,
                join: {
                    from: 'organizations.id',
                    to: 'userOrganizations.organizationId'
                }
            }
        };
    }
}

module.exports = Organization;
