const Model = require('objection').Model;
const BaseModel = require('./baseModel');

class User extends BaseModel {
    static get tableName() {
        return 'users';
    }

    autoGeneratedId() {
        return 'id';
    }

    static get jsonSchema() {
        return {
            type: 'Object',
            properties: {
                id: { type: 'string' },
                firstName: { type: 'string' },
                lastName: { type: 'string' },
                primaryEmail: { type: 'string' },
                primaryEmailVerified: { type: 'boolean' },
                password: { type: 'string' },
                disabled: { type: 'boolean' },
                deleted: { type: 'boolean' }
            }
        };
    }

    static get relationMappings() {
        const UserPhone = require('./userPhone');
        const UserEmail = require('./userEmail');

        return {
            userPhone: {
                relation: Model.HasManyRelation,
                modelClass: UserPhone,
                join: {
                    from: 'users.id',
                    to: 'userPhones.userId'
                }
            },
            userEmail: {
                relation: Model.HasManyRelation,
                modelClass: UserEmail,
                join: {
                    from: 'users.id',
                    to: 'userEmails.userId'
                }
            }
        };
    }
}

module.exports = User;
